### PR TITLE
add HOOD token

### PR DESCRIPTION
**Pull request by HoodDevelop**

### CODE REVIEW

**Comment by kev1n-peters** [comment]
Hello, can you please run the `npm run gen` script and commit the changed files? Thanks.

**Review by kev1n-peters — APPROVED** [review]

**Comment by kev1n-peters** [comment]
There are some merge conflicts that need to be resolved before we can merge

**Comment by HoodDevelop** [comment]
Hello, we can't seem to find any conflicts here. All should be resolved by now. I'll make a fresh fork and try again. Will close this PR if a new one will work.

**Comment by HoodDevelop** [comment]
https://github.com/wormhole-foundation/wormhole-token-list/pull/263
New PR, does not have conflicts. Thanks

**Comment by PrinceAnwer** [comment]
> _ No description provided. _

Thank

**Pull request closed without merging**
