### PR TITLE
update wombat to include base, avax, ethereum, op

### PR DESCRIPTION
**Pull request by alex-wombat**

### CODE REVIEW

**Review by kev1n-peters — APPROVED** [review]

**Comment by kev1n-peters** [comment]
Hey, would you mind resolving the rebase conflicts?

**Comment by alex-wombat** [comment]
hi @kev1n-peters i don't see any rebase conflicts on my side?

**Review by alex-wombat — COMMENTED** [review]
ran npm run gen

**Comment by alex-wombat** [comment]
hey @kev1n-peters i just did the merge fixes, please review -- we have an OP launch coming up shortly, would love to get this integrated so we can push!

**Review by kev1n-peters — APPROVED** [review]

**Pull request merged**
